### Modeling Approach

This notebook evaluates multiple regression models to predict residential home sale prices.

The target variable is the log-transformed sale price (`log_sale_price`).

Using a log transformation helps:

- reduce right-skew in price distributions
- stabilize variance
- improve regression model performance

Model performance is evaluated using:

• Mean Absolute Error (MAE)  
• R² score  
• Cross-validation performance

Since the model predicts log(price), predictions are exponentiated before calculating MAE to express errors in dollar terms.

##### Import libraries and data

In [1]:
# Core analysis libraries
import pandas as pd
import numpy as np

# Visualization libraries
import matplotlib.pyplot as plt
import seaborn as sns

# Improve plot styling
sns.set()

# Show all columns
pd.set_option('display.max_columns', None)

In [2]:
# File path locations
from pathlib import Path

# File paths
PROJECT_ROOT = Path.cwd().resolve().parent
CLEAN_DATA_DIR = PROJECT_ROOT / "data/clean_data"
RAW_DATA_DIR = PROJECT_ROOT / "data/raw_data"
MODELS_DIR = PROJECT_ROOT / "models"
SRC_DIR = PROJECT_ROOT / "src"
DEPLOYMENT_DIR = PROJECT_ROOT / "deployment"

In [3]:
data = pd.read_parquet(CLEAN_DATA_DIR / "03_feature_engineering.parquet")
data.head()

,log_gross_sqft,build_age_yrs,log_dist_to_station,neighborhood_bath_beach,neighborhood_bay_ridge,neighborhood_bedford_stuyvesant,neighborhood_bensonhurst,neighborhood_bergen_beach,neighborhood_boerum_hill,neighborhood_borough_park,neighborhood_brighton_beach,neighborhood_brooklyn_heights,neighborhood_brownsville,neighborhood_bushwick,neighborhood_canarsie,neighborhood_carroll_gardens,neighborhood_clinton_hill,neighborhood_cobble_hill,neighborhood_cobble_hill_west,neighborhood_coney_island,neighborhood_crown_heights,neighborhood_cypress_hills,neighborhood_dyker_heights,neighborhood_east_new_york,neighborhood_flatbush_central,neighborhood_flatbush_east,neighborhood_flatbush_lefferts_garden,neighborhood_flatbush_north,neighborhood_flatlands,neighborhood_fort_greene,neighborhood_gerritsen_beach,neighborhood_gowanus,neighborhood_gravesend,neighborhood_greenpoint,neighborhood_kensington,neighborhood_madison,neighborhood_manhattan_beach,neighborhood_marine_park,neighborhood_midwood,neighborhood_mill_basin,neighborhood_ocean_hill,neighborhood_ocean_parkway_north,neighborhood_ocean_parkway_south,neighborhood_old_mill_basin,neighborhood_park_slope,neighborhood_park_slope_south,neighborhood_prospect_heights,neighborhood_red_hook,neighborhood_seagate,neighborhood_sheepshead_bay,neighborhood_sunset_park,neighborhood_williamsburg_central,neighborhood_williamsburg_east,neighborhood_williamsburg_north,neighborhood_williamsburg_south,neighborhood_windsor_terrace,neighborhood_wyckoff_heights,building_class_category_one_family_dwellings,building_class_category_rentals_elevator_apartments,building_class_category_rentals_walkup_apartments,building_class_category_three_family_dwellings,building_class_category_two_family_dwellings,within_half_mi,log_sale_price
0,-0.918606,-0.032973,0.452206,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,5.999565
1,-0.519912,-0.032973,-0.050096,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,5.986772
2,-1.758724,-0.765916,-0.150647,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,5.934498
3,-0.244911,-0.032973,-0.953848,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,6.071882
4,0.290429,0.333499,0.528287,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,5.954243

In [4]:
data.shape

(4797, 64)

In [5]:
# Define target
y = data["log_sale_price"]

In [6]:
# Define features
X = data.drop("log_sale_price", axis=1)

### Train-Test Split

The dataset is divided into training and testing sets.

The training set is used to fit model parameters, while the testing set provides an unbiased evaluation of model performance.

This ensures that reported metrics reflect the model's ability to generalize to unseen data.

In [7]:
# Perform train/test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, 
    y,
    test_size=0.2,
    random_state=10
)

### Ordinary Least Squares (Baseline Model)

We begin with a standard linear regression model as a baseline.

Linear regression assumes:

• a linear relationship between predictors and the target  
• independence between predictors  
• constant variance of residuals

Performance metrics:

- Train Adjusted R²: **0.753**
- Test Adjusted R²: **0.719**
- Test MAE: **$345,856.74**

The baseline model provides a benchmark against which more flexible models can be compared.

##### OLS Regression -- Scikit-learn

In [8]:
# For Method config attributes always show
from sklearn import set_config
set_config(print_changed_only=False, display="diagram")

In [9]:
# Linear regression
from sklearn.linear_model import LinearRegression
ols_model = LinearRegression()
ols_model.fit(
    X_train, 
    y_train
)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, positive=False)

##### OLS Regression -- Statsmodels

In [10]:
import statsmodels.api as sm

In [11]:
# Add constants to X
X_train_sm = sm.add_constant(X_train).astype(float)
X_test_sm = sm.add_constant(X_test).astype(float)

In [12]:
sm_model = sm.OLS(y_train, X_train_sm).fit()
sm_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:         log_sale_price   R-squared:                       0.757
Model:                            OLS   Adj. R-squared:                  0.753
Method:                 Least Squares   F-statistic:                     193.0
Date:                Mon, 24 Aug 2026   Prob (F-statistic):               0.00
Time:                        17:25:02   Log-Likelihood:                 2702.9
No. Observations:                3837   AIC:                            -5282.
Df Residuals:                    3775   BIC:                            -4894.
Df Model:                          61
Covariance Type:            nonrobust
=======================================================================================================================
                                                          coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------------------------
const                                                   5.0421      0.008    657.864      0.000       5.027       5.057
log_gross_sqft                                          0.1333      0.003     44.712      0.000       0.127       0.139
build_age_yrs                                          -0.0016      0.002     -0.684      0.494      -0.006       0.003
log_dist_to_station                                     0.0114      0.004      3.080      0.002       0.004       0.019
neighborhood_bath_beach                                 0.0850      0.015      5.660      0.000       0.056       0.115
neighborhood_bay_ridge                                  0.0693      0.010      7.027      0.000       0.050       0.089
neighborhood_bedford_stuyvesant                         0.1292      0.008     15.351      0.000       0.113       0.146
neighborhood_bensonhurst                                0.0767      0.011      7.258      0.000       0.056       0.097
neighborhood_bergen_beach                              -0.0820      0.020     -4.108      0.000      -0.121      -0.043
neighborhood_boerum_hill                                0.3319      0.023     14.456      0.000       0.287       0.377
neighborhood_borough_park                               0.1544      0.009     16.620      0.000       0.136       0.173
neighborhood_brighton_beach                            -0.0981      0.026     -3.734      0.000      -0.150      -0.047
neighborhood_brooklyn_heights                           0.2999      0.040      7.474      0.000       0.221       0.379
neighborhood_brownsville                               -0.1710      0.016    -10.384      0.000      -0.203      -0.139
neighborhood_bushwick                                   0.0328      0.011      2.949      0.003       0.011       0.055
neighborhood_canarsie                                  -0.1195      0.010    -11.850      0.000      -0.139      -0.100
neighborhood_carroll_gardens                            0.4106      0.022     18.508      0.000       0.367       0.454
neighborhood_clinton_hill                               0.2540      0.022     11.790      0.000       0.212       0.296
neighborhood_cobble_hill                                0.3011      0.038      7.956      0.000       0.227       0.375
neighborhood_cobble_hill_west                           0.2277      0.038      6.045      0.000       0.154       0.302
neighborhood_coney_island                              -0.1360      0.033     -4.164      0.000      -0.200      -0.072
neighborhood_crown_heights                              0.0735      0.012      6.139      0.000       0.050       0.097
neighborhood_cypress_hills                             -0.1186      0.014     -8.539      0.000      -0.146      -0.091
neighborhood_dyker_heights                              0.1004      0.013      7.855      0.000       0.075       0.126
neighborhood_east_new_york                             -0.1395      0.009    -15.216      0.000      -0.157      -0.121
neighborhood_flatbush_central                           0.0512      0.013      3.901      0.000       0.025       0.077
neighborhood_flatbush_east                             -0.1005      0.009    -10.782      0.000      -0.119      -0.082
neighborhood_flatbush_lefferts_garden                   0.1337      0.019      7.150      0.000       0.097       0.170
neighborhood_flatbush_north                            -0.0794      0.014     -5.618      0.000      -0.107      -0.052
neighborhood_flatlands                                 -0.1029      0.019     -5.455      0.000      -0.140      -0.066
neighborhood_fort_greene                                0.3475      0.025     14.126      0.000       0.299       0.396
neighborhood_gerritsen_beach                           -0.0998      0.020     -4.979      0.000      -0.139      -0.060
neighborhood_gowanus                                    0.2314      0.026      8.834      0.000       0.180       0.283
neighborhood_gravesend                                  0.0373      0.011      3.376      0.001       0.016       0.059
neighborhood_greenpoint                                 0.2578      0.020     13.161      0.000       0.219       0.296
neighborhood_kensington                                 0.1415      0.032      4.432      0.000       0.079       0.204
neighborhood_madison                                    0.0356      0.013      2.695      0.007       0.010       0.062
neighborhood_manhattan_beach                            0.0923      0.022      4.238      0.000       0.050       0.135
neighborhood_marine_park                               -0.0471      0.012     -4.026      0.000      -0.070      -0.024
neighborhood_midwood                                    0.0592      0.012      4.781      0.000       0.035       0.083
neighborhood_mill_basin                                -0.0513      0.019     -2.675      0.007      -0.089      -0.014
neighborhood_ocean_hill                                -0.0185      0.014     -1.274      0.203      -0.047       0.010
neighborhood_ocean_parkway_north                        0.1878      0.012     15.273      0.000       0.164       0.212
neighborhood_ocean_parkway_south                        0.0935      0.018      5.224      0.000       0.058       0.129
neighborhood_old_mill_basin                            -0.1079      0.015     -7.030      0.000      -0.138      -0.078
neighborhood_park_slope                                 0.2955      0.016     18.902      0.000       0.265       0.326
neighborhood_park_slope_south                           0.2690      0.030      8.989      0.000       0.210       0.328
neighborhood_prospect_heights                           0.2735      0.045      6.080      0.000       0.185       0.362
neighborhood_red_hook                                   0.2550      0.032      7.900      0.000       0.192       0.318
neighborhood_seagate                                   -0.1326      0.036     -3.649      0.000      -0.204      -0.061
neighborhood_sheepshead_bay                            -0.0330      0.011     -2.878      0.004      -0.055      -0.011
neighborhood_sunset_park                                0.0883      0.012      7.430      0.000       0.065       0.112
neighborhood_williamsburg_central                       0.2339      0.038      6.199      0.000       0.160       0.308
neighborhood_williamsburg_east                          0.2514      0.022     11.382      0.000       0.208       0.295
neighborhood_williamsburg_north                         0.2292      0.040      5.755      0.000       0.151       0.307
neighborhood_williamsburg_south                         0.3170      0.038      8.390      0.000       0.243       0.391
neighborhood_windsor_terrace                            0.2030      0.020      9.939      0.000       0.163       0.243
neighborhood_wyckoff_heights                            0.0488      0.028      1.726      0.084      -0.007       0.104
building_class_category_one_family_dwellings            1.0479      0.008    137.717      0.000       1.033       1.063
building_class_category_rentals_elevator_apartments     1.0486      0.026     39.834      0.000       0.997       1.100
building_class_category_rentals_walkup_apartments       0.9506      0.008    121.670      0.000       0.935       0.966
building_class_category_three_family_dwellings          0.9865      0.007    144.046      0.000       0.973       1.000
building_class_category_two_family_dwellings            1.0085      0.006    157.313      0.000       0.996       1.021
within_half_mi                                          0.0388      0.008      4.617      0.000       0.022       0.055
==============================================================================
Omnibus:                       80.526   Durbin-Watson:                   2.064
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              108.960
Skew:                          -0.253   Prob(JB):                     2.19e-24
Kurtosis:                       3.652   Cond. No.                     5.95e+15
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.16e-28. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [13]:
# Create coefficients table
pvalues = sm_model.pvalues
coeffs = sm_model.params

sm_summary = pd.DataFrame({
    "Feature" : pvalues.index, 
    "Coefficient" : coeffs.values, 
    "p-value" : pvalues.values.round(3)
}).sort_values("p-value", ascending=False)

key_features = ["log_gross_sqft", "log_dist_to_station", "within_half_mi", "build_age_yrs"]

sm_summary["Percent Effect"] = ((10 ** sm_summary["Coefficient"] - 1) * 100).round(2)
sm_summary[sm_summary["Feature"].isin(key_features)]

                Feature  Coefficient  p-value  Percent Effect
2         build_age_yrs    -0.001630    0.494           -0.37
3   log_dist_to_station     0.011370    0.002            2.65
1        log_gross_sqft     0.133295    0.000           35.92
63       within_half_mi     0.038777    0.000            9.34

##### OLS predictions & assessments

In [14]:
y_pred_log = ols_model.predict(X_test)

y_pred = 10 ** y_pred_log
y_test_actual = 10 ** y_test

In [15]:
# MAE and RMSE

from sklearn.metrics import mean_absolute_error, mean_squared_error

ols_mae = mean_absolute_error(y_test_actual, y_pred)
ols_rmse = np.sqrt(mean_squared_error(y_test_actual, y_pred))

print("Test MAE ($):", round(ols_mae, 2))
print("Test RMSE ($):", round(ols_rmse, 2))

Test MAE ($): 345856.74
Test RMSE ($): 537067.26

In [16]:
# Median sales price
med_sale_price = (10 ** np.median(data["log_sale_price"])).round(2)
print("Median Brooklyn sales price ($):", med_sale_price)

Median Brooklyn sales price ($): 1260000.0

In [17]:
# Relative error
relative_error = (ols_mae / med_sale_price).round(2)
print("OLS relative error (%):", relative_error)

OLS relative error (%): 0.27

##### Model Baseline Metrics

In [18]:
# Train R-squared
ols_train_r2 = round(ols_model.score(X_train, y_train), 3)
print("Train R-squared:", ols_train_r2)

Train R-squared: 0.757

In [19]:
# Test R-squared
ols_test_r2 = round(ols_model.score(X_test, y_test), 3)
print("Test R-squared:", ols_test_r2)

Test R-squared: 0.737

In [20]:
# Adjusted R-Squared function
def adjusted_r2(r2, n, p):
    result = 1 - (1 - r2) * (n - 1)/(n - p - 1)
    return round(result, 3)

In [21]:
# Train adjusted R-squared
ols_train_adj_r2 = adjusted_r2(ols_train_r2, X_train.shape[0], X_train.shape[1])
print("Train Adjusted R-squared:", ols_train_adj_r2)

Train Adjusted R-squared: 0.753

In [22]:
# Test adjusted R-squared
ols_test_adj_r2 = adjusted_r2(ols_test_r2, X_test.shape[0], X_test.shape[1])
print("Test Adjusted R-squared:", ols_test_adj_r2)

Test Adjusted R-squared: 0.719

### Elastic Net Regression

Elastic Net combines L1 (Lasso) and L2 (Ridge) regularization.

This helps:

• reduce overfitting  
• manage multicollinearity  
• perform implicit feature selection

Cross-validation was used to select optimal regularization parameters.

Performance metrics:

- Train Adjusted R²: **0.753**
- Test Adjusted R²: **0.719**
- Test MAE: **$345,895.83**

Elastic Net often performs well when predictors are correlated.

In [23]:
# Scaling for Elastic Net
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [24]:
# Import library
from sklearn.linear_model import ElasticNetCV

In [25]:
# Elastic Net
elastic_model = ElasticNetCV(
    cv=5,
    l1_ratio=[0.1, 0.5, 0.9],
    max_iter=10000,
    verbose=0
)

elastic_model.fit(X_train_scaled, y_train)

ElasticNetCV(alphas=None, copy_X=True, cv=5, eps=0.001, fit_intercept=True,
             l1_ratio=[0.1, 0.5, 0.9], max_iter=10000, n_alphas=100,
             n_jobs=None, positive=False, precompute='auto', random_state=None,
             selection='cyclic', tol=0.0001, verbose=0)

In [26]:
# Best values for alpha (learning rate) and L1 Ratio (balance between Lasso and Ridge regression)
print("Regularization strength", (elastic_model.alpha_).round(6))
print("Lasso/Ridge balance is", elastic_model.l1_ratio_)

Regularization strength 0.001745
Lasso/Ridge balance is 0.1

In [27]:
# Predict Elastic Net results
y_pred_log_elastic = elastic_model.predict(X_test_scaled)

y_pred_elastic = 10 ** y_pred_log_elastic
y_test_actual_elastic = 10 ** y_test

In [28]:
# Elastic Net R-squared
elastic_train_r2 = elastic_model.score(X_train_scaled, y_train)
elastic_train_adj_r2 = adjusted_r2(elastic_train_r2, X_train.shape[0], X_train.shape[1])

# Elastic Net Adjusted R-squared
elastic_test_r2 = elastic_model.score(X_test_scaled, y_test)
elastic_test_adj_r2 = adjusted_r2(elastic_test_r2, X_test.shape[0], X_test.shape[1])

print("Elastic Net Train R-squared:", round(elastic_train_r2, 3))
print("Elastic Net Train Adjusted R-squared:", elastic_train_adj_r2)

print("Elastic Net Test R-squared:", round(elastic_test_r2, 3))
print("Elastic Net Test Adjusted R-squared:", elastic_test_adj_r2)

Elastic Net Train R-squared: 0.757
Elastic Net Train Adjusted R-squared: 0.753
Elastic Net Test R-squared: 0.738
Elastic Net Test Adjusted R-squared: 0.719

In [29]:
# MAE and RMSE
elastic_mae = mean_absolute_error(y_test_actual_elastic, y_pred_elastic)
print("Test Elastic MAE ($):", round(elastic_mae, 2))

Test Elastic MAE ($): 345895.83

### Random Forest Regression

Random Forest is an ensemble model that combines multiple decision trees.

Advantages:

• captures nonlinear relationships  
• robust to outliers  
• automatically models feature interactions

Performance metrics:

- Train Adjusted R²: **0.830**
- Test Adjusted R²: **0.701**
- Test MAE: **$361,345.14**

Feature importance analysis highlights the variables that contribute most to predictive accuracy.

In [30]:
# Import RF Regressor
from sklearn.ensemble import RandomForestRegressor

In [31]:
# Run RF Regression
rf_model = RandomForestRegressor(
    n_estimators=100,
    max_depth=None,
    min_samples_leaf=2,
    min_samples_split=5,
    n_jobs=-1,
    max_features="sqrt",
    random_state=42
)

rf_model.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='squared_error',
                      max_depth=None, max_features='sqrt', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_samples_leaf=2, min_samples_split=5,
                      min_weight_fraction_leaf=0.0, monotonic_cst=None,
                      n_estimators=100, n_jobs=-1, oob_score=False,
                      random_state=42, verbose=0, warm_start=False)

In [32]:
# RF Regressor results
y_pred_log_rf = rf_model.predict(X_test)

y_pred_rf = 10 ** y_pred_log_rf
y_test_actual_rf = 10 ** y_test

In [33]:
# RF Regressor R-squared
rf_train_r2 = rf_model.score(X_train, y_train)
rf_train_adj_r2 = adjusted_r2(rf_train_r2, X_train.shape[0], X_train.shape[1])

# RF Regressor AdjustedR-squared
rf_test_r2 = rf_model.score(X_test, y_test)
rf_test_adj_r2 = adjusted_r2(rf_test_r2, X_test.shape[0], X_test.shape[1])

print("Random Forest Regressor Train R-squared:", round(rf_train_r2, 3))
print("Random Forest Regression Train Adjusted R-squared:", rf_train_adj_r2)

print("Random Forest Regressor Test R-squared:", round(rf_test_r2, 3))
print("Random Forest Regression Test Adjusted R-squared:", rf_test_adj_r2)

Random Forest Regressor Train R-squared: 0.833
Random Forest Regression Train Adjusted R-squared: 0.83
Random Forest Regressor Test R-squared: 0.721
Random Forest Regression Test Adjusted R-squared: 0.701

In [34]:
# MAE
rf_mae = mean_absolute_error(y_test_actual_rf, y_pred_rf)

print("Test RF Regressor MAE ($):", round(rf_mae, 2))

Test RF Regressor MAE ($): 361345.14

### Gradient Boosted Trees (XGBoost)

XGBoost is a gradient boosting algorithm that builds trees sequentially.

Each tree attempts to correct the errors of the previous trees.

Advantages:

• strong predictive performance  
• handles nonlinear relationships  
• built-in regularization

Performance metrics:

- Train Adjusted R²: **0.816**
- Test Adjusted R²: **0.720**
- Test MAE: **$346,603.45**

Gradient boosting models frequently outperform simpler regression models in structured tabular datasets.

In [35]:
# Import library
from xgboost import XGBRegressor

In [36]:
# XGBoost
xgb_model = XGBRegressor(
    learning_rate=0.05, 
    n_estimators=500, 
    max_depth=4, 
    random_state=42,
    n_jobs=-1
)

xgb_model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=4,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=500,
             n_jobs=-1, num_parallel_tree=None, ...)

In [37]:
# Predict XGBoost results
y_pred_log_xgb = xgb_model.predict(X_test)

In [38]:
# Conversion to dollars
y_pred_xgb = 10 ** y_pred_log_xgb
y_test_actual = 10 ** y_test

In [39]:
# XGBoost R-squared
xgb_train_r2 = xgb_model.score(X_train, y_train)
xgb_train_adj_r2 = adjusted_r2(xgb_train_r2, X_train.shape[0], X_train.shape[1])

# XGBoost Adjusted R-squared
xgb_test_r2 = xgb_model.score(X_test, y_test)
xgb_test_adj_r2 = adjusted_r2(xgb_test_r2, X_test.shape[0], X_test.shape[1])

print("XGBoost Train R-squared:", round(xgb_train_r2, 3))
print("XGBoost Train Adjusted R-squared:", xgb_train_adj_r2)

print("XGBoost Test R-squared:", round(xgb_test_r2, 3))
print("XGBoost Test Adjusted R-squared:", xgb_test_adj_r2)

XGBoost Train R-squared: 0.819
XGBoost Train Adjusted R-squared: 0.816
XGBoost Test R-squared: 0.738
XGBoost Test Adjusted R-squared: 0.72

In [40]:
# MAE
xgb_mae = mean_absolute_error(y_test_actual, y_pred_xgb)

print("Test XGBoost MAE ($):", round(xgb_mae, 2))

Test XGBoost MAE ($): 346603.45

### Model Performance Comparison

Key observations:

• Tree-based models generally outperform linear models due to their ability to capture nonlinear relationships.

• The gap between training and testing performance provides insight into potential overfitting.

The final model is selected based on the best balance between predictive accuracy and generalization.

In [41]:
model_comp_data = [
    {"Model Name": "OLS", 
     "Train Adjusted R2": round(ols_train_adj_r2, 3), 
     "Test Adjusted R2": round(ols_test_adj_r2, 3), 
     "MAE": round(ols_mae, 2)},
    
    {"Model Name": "Elastic Net", 
     "Train Adjusted R2": round(elastic_train_adj_r2, 3), 
     "Test Adjusted R2": round(elastic_test_adj_r2, 3), 
     "MAE": round(elastic_mae, 2)},
    
    {"Model Name": "Random Forest", 
     "Train Adjusted R2": round(rf_train_adj_r2, 3), 
     "Test Adjusted R2": round(rf_test_adj_r2, 3), 
     "MAE": round(rf_mae, 2)},
    
    {"Model Name": "XGBoost", 
     "Train Adjusted R2": round(xgb_train_adj_r2, 3), 
     "Test Adjusted R2": round(xgb_test_adj_r2, 3), 
     "MAE": round(xgb_mae, 2)}
]

model_comparison = pd.DataFrame(model_comp_data)

### Final Model Selection

OLS was selected as the final model. While both OLS and ElasticNet finished with identical test adjusted R² scores, OLS had a slightly lower MAE, so this was chosn.

• Test Adjusted R² for OLS: **0.719**  
• Test MAE: **$345,856.74**

These results indicate that the model captures a substantial portion of price variation while maintaining reasonable prediction error.

Future improvements could include:

• additional location-based features  
• more granular spatial modeling  
• hyperparameter optimization

In [42]:
model_comparison.sort_values("MAE", ascending=True)

      Model Name  Train Adjusted R2  Test Adjusted R2        MAE
0            OLS              0.753             0.719  345856.74
1    Elastic Net              0.753             0.719  345895.83
3        XGBoost              0.816             0.720  346603.45
2  Random Forest              0.830             0.701  361345.14

### Save Final Model

In [43]:
import joblib
from sklearn.pipeline import Pipeline

In [44]:
# Train final model and fit on full dataset
final_model = LinearRegression()

final_model.fit(X, y)

# Save model
joblib.dump(final_model, MODELS_DIR / "home_price_model_ols.joblib")

['C:\\Users\\jac67\\Documents\\Data and Analytics\\Python\\brooklyn-home-sales-llm\\models\\home_price_model_ols.joblib']